"""Daily report HTML generator"""
import os
import logging
from datetime import datetime
from typing import List, Dict
from . import config

logger = logging.getLogger(__name__)

REPORT_TEMPLATE_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Brief - {date}</title>
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Daily Paper Brief</h1>
            <div class="subtitle">{date} - Strongly Correlated Electron Physics</div>
            <div class="stats">{count} new papers today</div>
        </div>
"""

REPORT_TEMPLATE_END = """
        <div class="footer">Generated by AI Assistant - Data source: arXiv</div>
    </div>
</body>
</html>"""


def _make_card(p):
    rating = p.get("value_rating") or 0
    stars = "★" * rating + "☆" * (5 - rating)
    one_line = p.get("one_line_value") or "(Pending AI analysis)"
    keywords = p.get("keywords", [])
    kw_tags = " ".join('<span class="tag">{0}</span>'.format(kw) for kw in keywords[:5])
    status_dot = "unread" if p.get("status") == "unread" else "read"

    return """        <div class="paper-card">
            <div class="paper-header">
                <span class="rating">{stars}</span>
                <span class="arxiv-id">arXiv:{aid}</span>
            </div>
            <h3 class="paper-title">
                <a href="/paper/{pid}">{title}</a>
            </h3>
            <div class="paper-authors">{authors}</div>
            <div class="paper-one-liner">{oneliner}</div>
            <div class="paper-keywords">{kw}</div>
            <div class="paper-footer">
                <span class="status-badge status-{stat}">{status}</span>
                <a href="/paper/{pid}" class="btn-detail">View detail →</a>
            </div>
        </div>
""".format(
        stars=stars, aid=p.get("arxiv_id", ""), pid=p["id"],
        title=p.get("title", ""),
        authors=str(p.get("authors", ""))[:200],
        oneliner=one_line, kw=kw_tags, stat=status_dot,
        status=p.get("status", "unread"),
    )


def generate_daily_report(papers: List[Dict], date: str = None) -> str:
    if date is None:
        date = datetime.now().strftime("%Y-%m-%d")

    reports_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), config.REPORTS_DIR)
    os.makedirs(reports_dir, exist_ok=True)

    sorted_papers = sorted(papers, key=lambda p: p.get("value_rating", 0) or 0, reverse=True)

    head = REPORT_TEMPLATE_HEAD.format(date=date, count=len(papers))
    body = "\n".join(_make_card(p) for p in sorted_papers)
    tail = REPORT_TEMPLATE_END
    html = head + body + tail

    filepath = os.path.join(reports_dir, "daily-{0}.html".format(date))
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
    logger.info("Report generated: {0}".format(filepath))
    return filepath
